version: '3.7'

services:
  curso:
    build:
      context: . 
      dockerfile: Dockerfile.local 
    volumes:
      - .:/curso
    ports:
      - 8888:8888
    command: pipenv run jupyter notebook notebooks --ip='0.0.0.0' --allow-root

